;;; package -- Summary
;;;
;;; Commentary:
;;; This is my init.el.  I put this here to make Flycheck shut up.

;;; Code:

;; Ignore stuff.  This is autogenerated.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" "c74e83f8aa4c78a121b52146eadb792c9facc5b1f02c917e3dbb454fca931223" "a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" "d677ef584c6dfc0697901a44b885cc18e206f05114c8a3b7fde674fce6180879" "cdbd0a803de328a4986659d799659939d13ec01da1f482d838b68038c1bb35e8" "8aebf25556399b58091e533e455dd50a6a9cba958cc4ebb0aab175863c25b9a4" default)))
 '(flyspell-delay 0.5)
 '(initial-frame-alist (quote ((fullscreen . maximized))))
 '(js2-bounce-indent-p t)
 '(js2-concat-multiline-strings (quote eol))
 '(js2-strict-missing-semi-warning nil)
 '(package-selected-packages
   (quote
    (flycheck-bashate flycheck-demjsonlint json-mode yaml-mode glsl-mode logstash-conf magit-gh-pulls kubernetes ensime helm-circe circe flycheck-irony company-irony-c-headers company-irony rtags cmake-ide cmake-mode groovy-mode smart-mode-line ponylang-mode flycheck-pony go-add-tags go-impl visual-regexp-steroids visual-regexp toml-mode helm-cider emacsql-mysql company-anaconda pydoc pyenv-mode python-mode py-yapf py-autopep8 spray ereader helm-pass org-bullets birds-of-paradise-plus-theme bookmark+ elfeed-org elfeed rainbow-blocks all-the-icons-dired ido-ubiquitous ido-yes-or-no ido-hacks f3 all-the-icons ripgrep rg rainbow-mode geiser paredit-menu paredit focus flyspell-lazy ace-flyspell vdiff dockerfile-mode pdf-tools latex-preview-pane company-math julia-shell ess nim-mode flycheck-nim idris-mode company-tern company-flow gotest ac-js2 eslint-fix color-theme-sanityinc-tomorrow zenburn-theme vue-mode undo-tree solarized-theme rats rainbow-delimiters racer mocha markdown-mode magit linum-relative goto-last-change go-rename go-guru go-eldoc go-dlv go-direx flycheck-rust flycheck-gometalinter flycheck-flow company-go cargo ack))))


;; MELPA
(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.org/packages/") t)

(package-initialize)

; (load-theme 'solarized-dark t)
; (load-theme 'solarized-light t)
; (load-theme 'zenburn t)
; (load-theme 'sanityinc-tomorrow-day t)
; (load-theme 'sanityinc-tomorrow-night t)
; (load-theme 'sanityinc-tomorrow-bright t)
; broken??
(require 'birds-of-paradise-plus-theme)
(load-theme birds-of-paradise-plus t)

;; Start in fullscreen
(defun my-fullscreen-hook ()
  "A hook which gets called after window setup."
  (custom-set-variables
    '(initial-frame-alist (quote ((fullscreen . maximized)))))
  (set-frame-parameter nil 'fullscreen 'fullboth)
  (tool-bar-mode -1)
)

(add-hook 'window-setup-hook 'my-fullscreen-hook)

;; Use whitespace mode to highlight lines extending beyond 72 columns.
(setq whitespace-line-column 72)
(setq whitespace-style '(face empty lines-tail trailing))
(global-whitespace-mode t)

;; Use relative line numbers
(linum-relative-mode)
(setq linum-relative-current-symbol "")
(ruler-mode 1)

;; Set up fonts.
(set-face-attribute 'default nil
		    :foundry "apple"
		    :family  "Go Mono"
		    :height  140
		    :weight  'light)

;; scroll one line at a time (less "jumpy" than defaults)
(setq mouse-wheel-scroll-amount '(2 ((shift) . 5))) ;; one line at a time
(setq mouse-wheel-progressive-speed nil) ;; don't accelerate scrolling
(setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse

(pdf-tools-install)

;; Undo tree
(undo-tree-mode)

(setq-default indent-tabs-mode nil)

;; Turn on smart-mode-line https://github.com/Malabarba/smart-mode-line
(sml/setup)
(setq sml/theme 'respectful)

;; Custom SML config
;; (setq sml/theme 'automatic
;;       sml/mode-width 'full
;;       sml/name-width '(0 . 20)
;;       sml/replacer-regexp-list
;;       '(("^~/org/" ":O:")
;;         ("^~/\\.emacs\\.d/" ":ED:")))

;; Broken
;; (add-hook 'dired-mode-hook 'all-the-icons-dired-mode)

;; Go setup
(defun my-go-mode-hook ()
  "Add this stuff to go-mode."
  ;; go-eldoc
  (go-eldoc-setup)
  ;; Use goimports instead of gofmt
  (setq gofmt-command "goimports")
  ;; Use smart tabs
  (setq indent-tabs-mode t)
  ;; gofmt-before-save
  (add-hook 'before-save-hook 'gofmt-before-save)
  ;; Go Guru identifier highlighting
  (add-hook 'go-mode-hook #'go-guru-hl-identifier-mode)
  ;; Godef jump / return hotkeys
  (local-set-key (kbd "C-x ,") 'godef-jump)
  (local-set-key (kbd "<s-mouse-1>") 'godef-jump)
  (local-set-key (kbd "C-x /") 'pop-tag-mark)
  ;; Use company-go
  (setq company-backends '(company-go))
  (company-mode)
  ;; linum-relative-mode
  (linum-relative-mode)
  (setq linum-relative-current-symbol "")
  ;; Rainbow delimiters
  (rainbow-delimiters-mode)
  ;; Compile and test
  (if (not (string-match "go" compile-command))
    (set (make-local-variable 'compile-command)
         (concat "go generate ./... && "
		 "go test --coverprofile=cover.out -check.vv && "
		 "go build ./...")))
  (local-set-key (kbd "C-x c") 'compile)
  ;; Ruler mode
  (ruler-mode 1)
  ;; Undo tree
  (undo-tree-mode)
)

;; Bind my Go setup to go-mode-hook
(add-hook 'go-mode-hook 'my-go-mode-hook)

(defun my-asm-mode-hook ()
  "This is documented at https://github.com/klauspost/asmfmt/."
  (set (make-local-variable 'gofmt-command) "asmfmt")
  (add-hook 'before-save-hook 'gofmt nil t)
)

(add-hook 'asm-mode-hook 'my-asm-mode-hook)

;; Julia setup
(defun my-julia-mode-hook ()
  "My julia-mode hook."
  (rainbow-delimiters-mode)
  (linum-relative-mode)
  (setq linum-relative-current-symbol "")
  (ruler-mode 1)
)

(add-hook 'julia-mode-hook 'my-julia-mode-hook)
(add-hook 'ess-mode-hook 'my-julia-mode-hook)

;; Bind rainbow-delimiters to elisp mode
(defun my-elisp-hook ()
  "My Emacs Lisp config hook."
  (rainbow-delimiters-mode)
  (linum-relative-mode)
  (setq linum-relative-current-symbol "")
  (paredit-mode)
)

(add-hook 'emacs-lisp-mode-hook 'my-elisp-hook)

;; Javascript stuff
(add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))

(defun my-vue-mode-hook ()
  "My vue-mode config hook."
  (linum-relative-mode)
  (setq linum-relative-current-symbol "")

  (require 'flycheck-flow)
  (flycheck-add-next-checker 'javascript-flow 'javascript-eslint)

  (ruler-mode 1)

  (undo-tree-mode)
)

(defun my-js2-hook ()
  "My js2-mode config hook."
  (setq js-indent-level 2)

  (setq company-backends '(company-tern company-flow))
  (company-mode)

  (linum-relative-mode)
  (setq linum-relative-current-symbol "")

  (ruler-mode 1)

  (undo-tree-mode)

  (add-hook 'after-save-hook 'eslint-fix nil t)
  (require 'flycheck-flow)
  (flycheck-add-next-checker 'javascript-flow 'javascript-eslint)
)

(add-hook 'vue-mode-hook 'my-vue-mode-hook)
(add-hook 'js2-mode-hook 'my-js2-hook)

(defun my-json-mode-hook ()
  "My json-mode config hook."
  (require 'flycheck-demjsonlint)
)

(add-hook 'json-mode-hook 'my-json-mode-hook)

(defun my-elixir-mode-hook ()
  "My 'elixir-mode' hook."
  (smartparens-mode)
  (sp-with-modes '(elixir-mode)
    (sp-local-pair "fn" "end"
           :when '(("SPC" "RET"))
           :actions '(insert navigate))
    (sp-local-pair "do" "end"
           :when '(("SPC" "RET"))
           :post-handlers '(sp-ruby-def-post-handler)
           :actions '(insert navigate))
  )
)

(add-hook 'elixir-mode 'my-elixir-mode-hook)

(defun my-rust-mode-hook ()
  "My 'rust-mode' hook."
  (setq indent-tabs-mode t)

  (define-key rust-mode-map (kbd "TAB") #'company-indent-or-complete-common)
  (setq company-tooltip-align-annotations t)

  (setq racer-rust-src-path (getenv "RUST_SRC_PATH"))
  (setq racer-cmd (concat (getenv "HOME") "/.cargo/bin/racer"))

  (setq rust-format-on-save t)

  (linum-relative-mode)
  (setq linum-relative-current-symbol "")

  (rainbow-delimiters-mode)

  (ruler-mode 1)
)

(add-hook 'flycheck-mode-hook 'flycheck-rust-setup)

(add-hook 'racer-mode-hook #'eldoc-mode)
(add-hook 'racer-mode-hook #'company-mode)

(add-hook 'rust-mode-hook #'racer-mode)

(require 'rust-mode)
(add-hook 'rust-mode-hook 'my-rust-mode-hook)

;; local configuration for TeX modes
(defun my-tex-mode-hook ()
  "My 'tex-mode' hook."
  (setq company-backends '(company-math-symbols-latex
                           company-latex-commands))
  (latex-preview-pane-enable)
  (company-mode)
)

(add-hook 'tex-mode-hook 'my-tex-mode-hook)

;; custom text-mode hook
(defun my-text-mode-hook ()
  "My 'text-mode' hook."

  (linum-relative-mode)
  (setq linum-relative-current-symbol "")

  (ruler-mode 1)

  (focus-mode)

  (ace-flyspell-setup)

  ; (require 'flyspell-lazy)
  ; (flyspell-lazy-mode 1)
  (flyspell-mode)
)

(add-hook 'text-mode-hook 'my-text-mode-hook)

(defun my-sh-mode-hook ()
  "My 'sh-mode' custom config hook."
  (require 'flycheck-bashate)
  (flycheck-bashate-setup)
  (linum-relative-mode)
)

(add-hook 'sh-mode-hook 'my-sh-mode-hook)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))

(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
(add-hook 'irony-mode-hook 'irony-eldoc)
(add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)

(defun my-cxx-mode ()
  "My C / C++ config hook."
  (cmake-ide-setup)
  (setq indent-tabs-mode t)
  (add-hook 'flycheck-mode-hook #'flycheck-irony-setup)
  (add-to-list 'company-backends '(company-irony-c-headers
				   company-irony))
  (c-set-style "K&R")
  ;; linum-relative-mode
  (linum-relative-mode)
  (setq linum-relative-current-symbol "")
  ;; irony-mode
  (irony-mode)
  ;; autocomplete
  (company-mode)
  ;;
  (rainbow-delimiters-mode)
  ;;
  (ruler-mode 1)
)

;; GLSL Mode
(add-to-list 'auto-mode-alist '("\\.glsl\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.vert\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.frag\\'" . glsl-mode))
(add-to-list 'auto-mode-alist '("\\.geom\\'" . glsl-mode))

(defun my-flycheck-rtags-setup ()
  "Set up Flycheck to use RTags overlays."
  (flycheck-select-checker 'rtags)
  ; RTags creates more accurate overlays.
  (setq-local flycheck-highlighting-mode nil)
  (setq-local flycheck-check-syntax-automatically nil)
)

;; c-mode-common-hook is also called by c++-mode
;(add-hook 'my-cxx-mode #'my-flycheck-rtags-setup)

(add-hook 'c++-mode-hook 'my-cxx-mode)
(add-hook 'c-mode-hook 'my-cxx-mode)

;; Global Flycheck
(add-hook 'after-init-hook #'global-flycheck-mode)

(defun my-python-mode ()
  "My custom Python mode."
  ; (add-to-list 'flycheck-disabled-checkers 'python-flake8)
  (py-yapf-enable-on-save)
  (anaconda-mode)
  (anaconda-eldoc-mode)
  (add-to-list 'flycheck-disabled-checkers 'python-pylint)
)

(eval-after-load "paredit.el"
   '(require 'paredit-menu))

(require 'org)
(require 'helm-org-rifle)

(defun my-org-mode-hook ()
  "My custom Org-mode hook."
  ; (org-bullets-mode 1)
  (define-key global-map "\C-cl" 'org-store-link)
  (define-key global-map "\C-ca" 'org-agenda)
  (focus-mode)
  (setq org-log-done t)
)

(setq org-agenda-files (list "~/meta/meta/org/meta.org"
                             "~/meta/meta/org/bookmarks.org"))

(add-hook 'org-mode-hook 'my-org-mode-hook)

(setq epg-gpg-program "gpg2")
(require 'helm-pass)

(require 'spray)
(global-set-key (kbd "C-c C-x s") 'spray-mode)

(defun my-ponylang-mode-hook ()
  "My custom ponylang-mode hook."
  (set-variable 'indent-tabs-mode nil)
  (set-variable 'tab-width 2)

  (if (not (string-match "ponyc" compile-command))
    (set (make-local-variable 'compile-command)
         "ponyc"))

  (local-set-key (kbd "C-x c") 'compile)

  (setq flycheck-pony-executable "/usr/local/bin/ponyc")
  
  ;; Ruler mode
  (ruler-mode 1)
)

(add-hook 'ponylang-mode-hook 'my-ponylang-mode-hook)

(provide 'init)
;;; init.el ends here

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(js2-error ((t (:underline "#c82829"))) t)
 '(js2-warning ((t (:underline (:color "gold" :style wave)))) t))
